#!/usr/bin/env python3
"""
generate_inventory.py — ARCHIVIRT Dynamic Inventory Generator
Queries Terraform state and generates Ansible inventory (hosts.ini).

Author: Яснеманегре САВАДОГО (Аспирант СПбГУПТД)
Project: ARCHIVIRT
"""

import json
import subprocess
import sys
import argparse
import os
from pathlib import Path

# ── Default network configuration ─────────────────────────────────────────────
DEFAULTS = {
    "manager_ip":   "10.0.5.10",
    "attacker_ip":  "10.0.4.10",
    "monitor_ip":   "10.0.3.10",
    "target_01_ip": "10.0.2.11",
    "target_02_ip": "10.0.2.12",
    "target_03_ip": "10.0.2.13",
    "ansible_user": "ubuntu",
    "ssh_key":      "~/.ssh/archivirt_key",
}


def get_terraform_outputs(terraform_dir: str) -> dict:
    """Read IP addresses from Terraform state outputs."""
    try:
        result = subprocess.run(
            ["terraform", "output", "-json"],
            cwd=terraform_dir,
            capture_output=True,
            text=True,
            check=True,
        )
        raw = json.loads(result.stdout)
        outputs = {k: v["value"] for k, v in raw.items()}
        print(f"[+] Loaded {len(outputs)} outputs from Terraform state.")
        return outputs
    except subprocess.CalledProcessError as e:
        print(f"[!] terraform output failed: {e.stderr.strip()}")
        print("[!] Falling back to default IPs.")
        return {}
    except FileNotFoundError:
        print("[!] terraform not found in PATH. Using default IPs.")
        return {}
    except json.JSONDecodeError:
        print("[!] Failed to parse Terraform JSON output. Using default IPs.")
        return {}


def build_inventory(ips: dict, ssh_user: str, ssh_key: str) -> str:
    """Build Ansible inventory INI string from IP map."""

    def ip(key, fallback):
        return ips.get(key, DEFAULTS[fallback])

    manager_ip   = ip("manager_ip",   "manager_ip")
    attacker_ip  = ip("attacker_ip",  "attacker_ip")
    monitor_ip   = ip("monitor_ip",   "monitor_ip")
    target_01_ip = ip("target_01_ip", "target_01_ip")
    target_02_ip = ip("target_02_ip", "target_02_ip")
    target_03_ip = ip("target_03_ip", "target_03_ip")

    inventory = f"""# ============================================================
# ARCHIVIRT — Auto-Generated Ansible Inventory
# Generated by: scripts/generate_inventory.py
# Author: Яснеманегре САВАДОГО (Аспирант СПбГУПТД)
# ============================================================

[manager]
manager ansible_host={manager_ip}

[attacker]
attacker ansible_host={attacker_ip}

[monitor]
monitor ansible_host={monitor_ip}

[targets]
target-01 ansible_host={target_01_ip}
target-02 ansible_host={target_02_ip}
target-03 ansible_host={target_03_ip}

[all:vars]
ansible_user={ssh_user}
ansible_ssh_private_key_file={ssh_key}
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_python_interpreter=/usr/bin/python3

[targets:vars]
target_subnet=10.0.2.0/24

[monitor:vars]
monitor_iface=ens4
ids_log_dir=/var/log/ids

[manager:vars]
influxdb_url=http://localhost:8086
grafana_port=3000

[attacker:vars]
wordlist_dir=/opt/archivirt/wordlists
tools_dir=/opt/archivirt/tools
results_dir=/opt/archivirt/results
"""
    return inventory


def test_connectivity(ips: dict, ssh_user: str, ssh_key: str) -> None:
    """Ping each VM to verify reachability before writing inventory."""
    print("\n[*] Testing VM connectivity...")
    all_ok = True
    for role, ip_key, fallback in [
        ("manager",   "manager_ip",   "manager_ip"),
        ("attacker",  "attacker_ip",  "attacker_ip"),
        ("monitor",   "monitor_ip",   "monitor_ip"),
        ("target-01", "target_01_ip", "target_01_ip"),
        ("target-02", "target_02_ip", "target_02_ip"),
        ("target-03", "target_03_ip", "target_03_ip"),
    ]:
        ip = ips.get(ip_key, DEFAULTS[fallback])
        result = subprocess.run(
            ["ping", "-c", "1", "-W", "2", ip],
            capture_output=True,
        )
        status = "✓ reachable" if result.returncode == 0 else "✗ UNREACHABLE"
        if result.returncode != 0:
            all_ok = False
        print(f"  {role:12s} ({ip}): {status}")

    if not all_ok:
        print("\n[!] Warning: some VMs are unreachable. Check that Terraform has provisioned them.")
    else:
        print("\n[+] All VMs reachable.")


def main():
    parser = argparse.ArgumentParser(
        description="Generate Ansible inventory from Terraform state or defaults."
    )
    parser.add_argument(
        "--terraform-dir", "-t",
        default="terraform/",
        help="Path to Terraform directory (default: terraform/)",
    )
    parser.add_argument(
        "--output", "-o",
        default="ansible/inventory/hosts.ini",
        help="Output inventory file path (default: ansible/inventory/hosts.ini)",
    )
    parser.add_argument(
        "--ssh-user",
        default=DEFAULTS["ansible_user"],
        help=f"SSH user for Ansible (default: {DEFAULTS['ansible_user']})",
    )
    parser.add_argument(
        "--ssh-key",
        default=DEFAULTS["ssh_key"],
        help=f"SSH private key path (default: {DEFAULTS['ssh_key']})",
    )
    parser.add_argument(
        "--test-connectivity",
        action="store_true",
        help="Ping VMs before writing inventory",
    )
    parser.add_argument(
        "--use-defaults",
        action="store_true",
        help="Skip Terraform query and use built-in default IPs",
    )
    args = parser.parse_args()

    print("=" * 60)
    print("ARCHIVIRT — Inventory Generator")
    print("=" * 60)

    # Resolve IPs
    if args.use_defaults:
        print("[*] Using built-in default IPs.")
        ips = {}
    else:
        tf_dir = os.path.abspath(args.terraform_dir)
        print(f"[*] Reading Terraform outputs from: {tf_dir}")
        ips = get_terraform_outputs(tf_dir)

    # Optional connectivity test
    if args.test_connectivity:
        test_connectivity(ips, args.ssh_user, args.ssh_key)

    # Build and write inventory
    inventory_content = build_inventory(ips, args.ssh_user, args.ssh_key)
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(inventory_content)

    print(f"\n[+] Inventory written to: {output_path}")
    print("\n--- Inventory Preview ---")
    print(inventory_content)


if __name__ == "__main__":
    main()
